// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  //
  // DB TOGGLE: set VITE_USE_PERSONAL_SUPABASE=true (and the
  // VITE_PERSONAL_SUPABASE_* vars below) to point the whole app at a
  // different Supabase project instead of the original shared one. This is
  // a build-time flag — flipping it requires a redeploy to take effect, it
  // is not a live in-browser switch. Defaults to false (unchanged, shared
  // project) so this is a no-op unless deliberately turned on.
  const usePersonal =
    (import.meta.env.VITE_USE_PERSONAL_SUPABASE || process.env.USE_PERSONAL_SUPABASE) === "true";

  const SUPABASE_URL = usePersonal
    ? import.meta.env.VITE_PERSONAL_SUPABASE_URL || process.env.PERSONAL_SUPABASE_URL
    : import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = usePersonal
    ? import.meta.env.VITE_PERSONAL_SUPABASE_PUBLISHABLE_KEY ||
      process.env.PERSONAL_SUPABASE_PUBLISHABLE_KEY
    : import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (usePersonal) {
    console.info(
      "[Supabase] Using the PERSONAL Supabase project (VITE_USE_PERSONAL_SUPABASE=true).",
    );
  }

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const prefix = usePersonal ? "PERSONAL_" : "";
    const missing = [
      ...(!SUPABASE_URL ? [`${prefix}SUPABASE_URL`] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? [`${prefix}SUPABASE_PUBLISHABLE_KEY`] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}.${usePersonal ? " VITE_USE_PERSONAL_SUPABASE is true but the personal project credentials are not set." : " Connect Supabase in Lovable Cloud."}`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
